# Generated by Django 4.1.4 on 2022-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_category_coffeeshop_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='categories',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='categories',
            field=models.ManyToManyField(to='coffeeshop.category'),
        ),
    ]
