# Generated by Django 4.1.4 on 2023-02-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeshop", "0003_remove_item_category_category_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="item",
            new_name="items",
        ),
    ]
