# Generated by Django 4.1.4 on 2022-12-17 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_alter_category_options_remove_coffeeshop_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='categories',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.category'),
        ),
    ]
