# Generated by Django 4.1.4 on 2022-12-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_remove_coffeeshop_categories_coffeeshop_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='categories',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='categories',
            field=models.ManyToManyField(to='coffeeshop.category'),
        ),
    ]
