# Generated by Django 4.1.4 on 2023-02-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeshop", "0005_remove_category_items_category_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
