# Generated by Django 4.1.4 on 2022-12-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_item_alter_category_options_category_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='logo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
