# Generated by Django 4.1.4 on 2022-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0007_alter_coffeeshop_logo_url_alter_item_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
