# Generated by Django 4.1.4 on 2022-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0008_alter_coffeeshop_logo_url_alter_item_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(to='coffeeshop.item'),
        ),
    ]
