# Generated by Django 4.1.4 on 2022-12-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0011_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
    ]
