# Generated by Django 4.1.4 on 2022-12-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0012_remove_category_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(to='coffeeshop.item'),
        ),
    ]
