# Generated by Django 4.1.4 on 2022-12-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0014_alter_coffeeshop_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='categories',
            field=models.ManyToManyField(to='coffeeshop.category'),
        ),
    ]
