# Generated by Django 4.1.4 on 2023-01-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeshop", "0015_alter_coffeeshop_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="items",
        ),
    ]
