# Generated by Django 4.1.4 on 2023-01-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0007_alter_owner_id"),
        ("coffeeshop", "0016_remove_category_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coffeeshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_url", models.URLField()),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
