# Generated by Django 4.1.4 on 2023-02-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeshop", "0018_delete_category_delete_item_coffeeshop_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
        migrations.RemoveField(
            model_name="item",
            name="photo_url",
        ),
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="categories",
            field=models.ManyToManyField(to="coffeeshop.category"),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="coffeeshop.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
