# Generated by Django 4.1.4 on 2022-12-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffeeshop', '0015_alter_coffeeshop_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('coffeeshop_owned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.coffeeshop')),
            ],
        ),
    ]
