# Generated by Django 4.1.4 on 2022-12-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0015_alter_coffeeshop_categories'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Owner',
        ),
    ]
