# Generated by Django 4.1.4 on 2022-12-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0015_alter_coffeeshop_categories'),
        ('owner', '0003_alter_owner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='coffeeshop_owned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.coffeeshop'),
        ),
    ]
