# Generated by Django 4.1.4 on 2023-01-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0004_alter_owner_coffeeshop_owned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="coffeeshop_owned",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="password",
        ),
    ]
