# Generated by Django 4.1.4 on 2023-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0005_remove_owner_coffeeshop_owned_remove_owner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
