# Generated by Django 4.1.4 on 2023-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0006_alter_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
