# Generated by Django 4.1.4 on 2022-12-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
